import { GlobalContextProvider } from "@/containers/GlobalContext";
import "./globals.css";
import NavBar from "@/components/Navbar/index";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="h-screen w-screen dark:bg-black dark:text-white bg-white text-black duration-700 transition-colors ease-out">
                <GlobalContextProvider>
                    <div className="w-full h-full flex">
                        <NavBar />
                        {children}
                    </div>
                </GlobalContextProvider>
                <Toaster />
            </body>
        </html>
    );
}
